trigger:
  branches:
    include:
      - '*'  # Runs on every commit to any branch

pool:
  vmImage: 'windows-latest'  # Uses Microsoft-hosted agent

steps:
  - script: echo "Starting Pipeline Execution"
    displayName: 'Start Pipeline'

  - script: echo "Running Some Build or Tests..."
    displayName: 'Run Build'

  - powershell: |
      $smtpServer = "intrelay.allscripts.com"
      $smtpPort = 587
      $smtpUser = "anonymous"  # Replace with your email
      $smtpPassword = " "  # Use secret variable for password
      $from = "Ready-team@alterahealth.com"
      $to = "<%=instance.createdByEmail%>"  # Replace with recipient email
      $subject = "Azure DevOps Pipeline Status"
      $body = "The pipeline has completed execution. View the details here: $(Build.BuildUri)"

      # Create SMTP client object
      $smtp = New-Object System.Net.Mail.SmtpClient($smtpServer, $smtpPort)
      $smtp.Credentials = New-Object System.Net.NetworkCredential($smtpUser, $smtpPassword)
      $smtp.EnableSsl = $true

      # Create email message object
      $message = New-Object System.Net.Mail.MailMessage($from, $to, $subject, $body)

      # Send email
      $smtp.Send($message)
    displayName: 'Send Email Notification'
