trigger:
  branches:
    include:
      - '*'  # Runs on every commit to any branch

pool:
  name: 'dbMotion_Pool_Net6'

steps:
  - script: echo "Starting Pipeline Execution"
    displayName: 'Start Pipeline'
    
  - powershell: |
      Write-Host "Running on server: $(Agent.MachineName)"
    displayName: "Show Server Name"
    
  - powershell: |
      $folderPath = "C:\Temp\AnnasTest\"
      $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
      $filePath = "$folderPath\Run_$timestamp.txt"

      # Create a new text file with the timestamp
      "This file was created on: $timestamp" | Out-File -FilePath $filePath

      Write-Host "File created: $filePath"
    displayName: "Create Folder and Timestamped File"
