trigger:
  branches:
    include:
      - '*'  # Runs on every commit to any branch

pool:
  vmImage: 'ubuntu-latest'  # Uses Microsoft-hosted agent

steps:
  - script: echo "Starting Pipeline Execution"
    displayName: 'Start Pipeline'

  - script: echo "Running Some Build or Tests..."
    displayName: 'Run Build'

  - powershell: |
$User = 'anonymous'

$MailServer = "intrelay.allscripts.com"
$From = "Ready-team@alterahealth.com"
$To = "<%=instance.createdByEmail%>"
$Subject = "Your pipeline is working"
$MailBody = "The pipeline has completed execution. View the details here: $(Build.BuildUri)"
      # Create SMTP client object
      $smtp = New-Object System.Net.Mail.SmtpClient($MailServer, '587')
      $smtp.Credentials = New-Object System.Net.NetworkCredential($User, " ")
      $smtp.EnableSsl = $true

      # Create email message object
      $message = New-Object System.Net.Mail.MailMessage($From, $To, $Subject, $MailBody)

      # Send email
      $smtp.Send($message)
    displayName: 'Send Email Notification'
