trigger:
  branches:
    include:
      - '*'  # Runs on every commit to any branch

pool:
  name: 'dbMotion_Pool_Net6'

steps:
  - script: echo "Starting Pipeline Execution"
    displayName: 'Start Pipeline'
    
  - powershell: |
      Write-Host "Running on server: $(Agent.MachineName)"
    displayName: "Show Server Name"
    
  - powershell: src/my-script.ps1
    displayName: "Run Script from Repository"
